sonar.projectKey=mmaudet_visio-mobile
sonar.organization=mmaudet
sonar.projectName=visio-mobile

sonar.sources=crates,android/app/src/main,crates/visio-desktop/frontend/src
sonar.exclusions=**/target/**,**/node_modules/**,**/build/**,**/uniffi/**,**/generated/**

# Exclude vendored third-party code from all analysis
sonar.global.exclusions=vendor/**

sonar.tests=crates/visio-core/tests
sonar.test.exclusions=**/test/**,**/*_test.*,**/tests/**

sonar.sourceEncoding=UTF-8
