//! PKCE (Proof Key for Code Exchange) helpers for OAuth2 native-app login.
//!
//! Implements RFC 7636 §4.1-4.2: generate a random 32-byte `code_verifier`
//! and its SHA-256 `code_challenge`, plus a `state` for CSRF protection.

use base64::{Engine, engine::general_purpose::URL_SAFE_NO_PAD};
use rand::{RngCore, rngs::OsRng};
use sha2::{Digest, Sha256};

/// PKCE pair + state generated by the client before opening the SSO browser.
///
/// `Debug` is intentionally redacted because the `verifier` is the secret
/// half of RFC 7636 §4.1 — whoever sees it can complete the token exchange
/// for the matching challenge. `challenge` and `state` are also redacted for
/// uniformity (they are sent over the URL in cleartext anyway, but seeing
/// them in logs serves no debugging purpose).
#[derive(Clone)]
pub struct PkceChallenge {
    /// Kept secret by the client; sent only in the final token exchange.
    pub verifier: String,
    /// Sent to the server as `code_challenge` (S256).
    pub challenge: String,
    /// Anti-CSRF nonce, echoed back by the server in the deep-link callback.
    pub state: String,
}

impl std::fmt::Debug for PkceChallenge {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PkceChallenge")
            .field("verifier", &"<redacted>")
            .field("challenge", &"<redacted>")
            .field("state", &"<redacted>")
            .finish()
    }
}

impl PkceChallenge {
    /// Generate a fresh PKCE pair with 256-bit entropy.
    pub fn generate() -> Self {
        let verifier = random_base64url(32);
        let state = random_base64url(32);
        let challenge = sha256_base64url(&verifier);
        Self {
            verifier,
            challenge,
            state,
        }
    }
}

fn random_base64url(byte_len: usize) -> String {
    let mut buf = vec![0u8; byte_len];
    // OsRng pulls directly from the OS CSPRNG (getrandom on Linux, SecRandom
    // on iOS/macOS, BCryptGenRandom on Windows). Avoids any ambiguity about
    // ThreadRng reseed cadence for PKCE-grade secrets.
    OsRng.fill_bytes(&mut buf);
    URL_SAFE_NO_PAD.encode(&buf)
}

fn sha256_base64url(input: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(input.as_bytes());
    URL_SAFE_NO_PAD.encode(hasher.finalize())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn challenge_matches_sha256_of_verifier() {
        let p = PkceChallenge::generate();
        assert_eq!(sha256_base64url(&p.verifier), p.challenge);
    }

    #[test]
    fn fields_are_43_chars_base64url() {
        // 32 random bytes → 43 chars base64url no-pad.
        let p = PkceChallenge::generate();
        assert_eq!(p.verifier.len(), 43);
        assert_eq!(p.state.len(), 43);
        assert_eq!(p.challenge.len(), 43);
        for s in [&p.verifier, &p.state, &p.challenge] {
            assert!(
                s.chars()
                    .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_'),
                "non-url-safe char in {}",
                s
            );
        }
    }

    #[test]
    fn two_challenges_differ() {
        let a = PkceChallenge::generate();
        let b = PkceChallenge::generate();
        assert_ne!(a.verifier, b.verifier);
        assert_ne!(a.state, b.state);
    }

    #[test]
    fn known_vector_rfc7636() {
        // RFC 7636 Appendix B reference vector.
        let verifier = "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk";
        let expected = "E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM";
        assert_eq!(sha256_base64url(verifier), expected);
    }
}
